name: Schedule Notion movie faster Build

on:
  #  issues:
  #    types: [opened, edited, closed, reopened]
  #  issue_comment:
  #    types: [created, edited, deleted]
  workflow_dispatch:
  schedule:
   - cron: '*/60 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TMDB_KEY: ${{ secrets.TMDB_KEY }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # maven 缓存
      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package



      - name: Run Spring Boot application
        run: java -jar target/notion-movie-faster.jar
